// Mock codegen output — in production this will be generated by `zodiac-os codegen`
// and written to .zodiac-os/org-data

export const safes = {
  "GG DAO": {
    address: "0xaaaa00000000000000000000000000000000aaaa",
    chain: 1,
    nonce: 0n,
    threshold: 3,
    owners: [
      "0xbbbb00000000000000000000000000000000bbbb",
      "0xcccc00000000000000000000000000000000cccc",
      "0xdddd00000000000000000000000000000000dddd",
    ],
    modules: [],
    vault: true,
  },
  Treasury: {
    address: "0xeeee00000000000000000000000000000000eeee",
    chain: 1,
    nonce: 1n,
    threshold: 2,
    owners: [
      "0xbbbb00000000000000000000000000000000bbbb",
      "0xcccc00000000000000000000000000000000cccc",
    ],
    modules: [],
    vault: true,
  },
} as const;

export const users = {
  "jan@gnosisguild.org": {
    fullName: "Jan-Felix Schwarz",
    address: "0xbbbb00000000000000000000000000000000bbbb" as `0x${string}`,
  },
  "Alice Example": {
    fullName: "Alice Example",
    address: "0xcccc00000000000000000000000000000000cccc" as `0x${string}`,
  },
} as const;
