// Mock codegen output — in production this will be generated by `zodiac-os pull-org`
// and written to .zodiac-os/types/index.ts

export const users = {
  'Alice Sample': {
    id: 'user-a',
    fullName: 'Alice Sample',
    personalSafes: {
      1: {
        address: '0xaaaa00000000000000000000000000000000aaaa',
        active: true,
      },
    },
  },
  'Bob Test': {
    id: 'user-b',
    fullName: 'Bob Test',
    personalSafes: {
      1: {
        address: '0xbbbb00000000000000000000000000000000bbbb',
        active: true,
      },
    },
  },
} as const

export const vaults = {
  GG: {
    workspaceId: 'ws-1',
    workspaceName: 'GG',
    vaults: {
      'GG DAO': {
        id: 'vault-1',
        label: 'GG DAO',
        address: '0xcccc00000000000000000000000000000000cccc',
        chainId: 1,
        threshold: 3,
        owners: [
          '0xaaaa00000000000000000000000000000000aaaa',
          '0xbbbb00000000000000000000000000000000bbbb',
          '0xdddd00000000000000000000000000000000dddd',
        ],
        modules: [],
      },
      Treasury: {
        id: 'vault-2',
        label: 'Treasury',
        address: '0xeeee00000000000000000000000000000000eeee',
        chainId: 1,
        threshold: 2,
        owners: [
          '0xaaaa00000000000000000000000000000000aaaa',
          '0xbbbb00000000000000000000000000000000bbbb',
        ],
        modules: [],
      },
    },
  },
} as const
