name: Continuous integration checks

on: [push]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('bun.lockb', 'bunfig.toml') }}
      - name: Install dependencies
        run: bun install
      - name: Check formatting
        run: bun check:format
      - name: Build package
        run: bun run build

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('bun.lockb', 'bunfig.toml') }}
      - name: Install dependencies
        run: bun install
      - name: Run tests
        run: bun run test
